config {
    type: "table",
    schema: "silver",
    name: "order_items",

    assertions: {
        uniqueKey: ["id"],

        nonNull: [
            "id",
            "order_id",
            "user_id",
            "product_id",
            "created_at",
            "sale_price",
        ],

        rowConditions: [
            "sale_price >= 0",
            "delivered_at IS NULL OR (shipped_at IS NOT NULL AND delivered_at >= shipped_at)",
            "returned_at IS NULL OR (delivered_at IS NOT NULL AND returned_at >= delivered_at)"
        ]
    }
}

SELECT
  id,
  order_id,
  user_id,
  product_id,
  inventory_item_id,
  UPPER(TRIM(status)) AS status,
  DATE(created_at) AS order_date,
  created_at,
  shipped_at,
  delivered_at,
  returned_at,
  ROUND(CAST(sale_price AS NUMERIC), 2) AS sale_price,
  CURRENT_TIMESTAMP() AS processed_at,
  'THELOOK' AS source_system
FROM
  ${ref("bronze", "order_items")}
WHERE
  id IS NOT NULL
  AND order_id IS NOT NULL
  AND user_id IS NOT NULL
  AND product_id IS NOT NULL
  AND sale_price IS NOT NULL
  AND sale_price >= 0
